init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install each-exec mocha

build: off

test_script:
  - ps: 'node node_modules\.bin\_mocha test\test.js # PowerShell'
  - cmd: node node_modules\.bin\_mocha test\test.js

cache:
  - node_modules
